/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIKeyboardCache : NSObject {
    NSMutableSet * _activeRenderers;
    // _UIActionWhenIdle * _idleAction;
    NSSet * _layouts;
    // TIImageCacheClient * _store;
}

// @property (nonatomic, retain) _UIActionWhenIdle *idleAction;

+ (UIKeyboardCache *)sharedInstance;

- (void)purge;

@end
