/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIKeyboardTouchInfo : NSObject {
    
}

@property (nonatomic) CGPoint initialDragPoint;
@property (nonatomic) CGPoint initialPoint;
@property (nonatomic, assign) bool fpAllow;

@end
