/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIKBTree : NSObject <NSCopying> {
    bool  _isFloating;
    NSMutableDictionary * cache;
    NSString * effectiveLayoutTag;
    NSString * layoutTag;
    NSString * name;
    NSMutableDictionary * properties;
    NSMutableArray * subtrees;
    int  type;
}

@property (nonatomic, retain) NSMutableDictionary *cache;
@property (nonatomic, retain) NSString *effectiveLayoutTag;
@property (nonatomic) bool isFloating;
@property (nonatomic, retain) NSString *layoutTag;
@property (nonatomic, retain) NSString *name;
@property (nonatomic, retain) NSMutableDictionary *properties;
@property (nonatomic, retain) NSMutableArray *subtrees;
@property (nonatomic) int type;

- (id)alternateKeyplaneName;
- (id)cachedGestureLayout;
- (id)displayString;
- (id)gestureKeyplaneName;
- (id)keySet;
- (id)representedString;
- (int)displayType;
- (int)displayTypeHint;
- (long long)selectedVariantIndex;
- (void)setDisplayTypeHint:(int)arg1;
- (void)setGestureKey:(id)arg1;
- (bool)setObject:(id)arg1 forProperty:(id)arg2;
- (void)setSecondaryDisplayStrings:(id)arg1;
- (void)setSecondaryRepresentedStrings:(id)arg1;
- (id)shiftAlternateKeyplaneName;
- (id)stringForProperty:(id)arg1;
- (id)subtreeWithName:(id)arg1;
@end
