/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIKBTextStyle : NSObject <NSCopying> {
    long long  _alignment;
    unsigned long long  _anchorCorner;
    NSString * _etchColor;
    CGPoint  _etchOffset;
    NSString * _fontName;
    double  _fontSize;
    double  _fontWeight;
    bool  _ignoreTextMarginOnKey;
    double  _imageScale;
    double  _kerning;
    double  _minFontSize;
    double  _pathWeight;
    long long  _selector;
    NSString * _textColor;
    CGPoint  _textOffset;
    double  _textOpacity;
}

@property (nonatomic) long long alignment;
@property (nonatomic) unsigned long long anchorCorner;
@property (nonatomic, retain) NSString *etchColor;
@property (nonatomic) CGPoint etchOffset;
@property (nonatomic, retain) NSString *fontName;
@property (nonatomic) double fontSize;
@property (nonatomic) double fontWeight;
@property (nonatomic) bool ignoreTextMarginOnKey;
@property (nonatomic) double imageScale;
@property (nonatomic) double kerning;
@property (nonatomic) double minFontSize;
@property (nonatomic) double pathWeight;
@property (nonatomic) long long selector;
@property (nonatomic, retain) NSString *textColor;
@property (nonatomic) CGPoint textOffset;
@property (nonatomic) double textOpacity;

+ (id)styleWithFontName:(id)arg1 withFontSize:(double)arg2;
+ (id)styleWithTextColor:(id)arg1;

- (long long)alignment;
- (unsigned long long)anchorCorner;
- (id)copyWithZone:(NSZone *)arg1;
- (void)dealloc;
- (NSString *)description;
- (NSString *)etchColor;
- (CGPoint)etchOffset;
- (NSString *)fontName;
- (double)fontSize;
- (double)fontWeight;
- (bool)ignoreTextMarginOnKey;
- (double)imageScale;
- (id)init;
- (bool)isEqual:(id)arg1;
- (double)kerning;
- (double)minFontSize;
- (void)overlayWithStyle:(id)arg1;
- (double)pathWeight;
- (long long)selector;
- (void)setAlignment:(long long)arg1;
- (void)setAnchorCorner:(unsigned long long)arg1;
- (void)setEtchColor:(NSString *)arg1;
- (void)setEtchOffset:(CGPoint)arg1;
- (void)setFontName:(NSString *)arg1;
- (void)setFontSize:(double)arg1;
- (void)setFontWeight:(double)arg1;
- (void)setIgnoreTextMarginOnKey:(bool)arg1;
- (void)setImageScale:(double)arg1;
- (void)setKerning:(double)arg1;
- (void)setMinFontSize:(double)arg1;
- (void)setPathWeight:(double)arg1;
- (void)setSelector:(long long)arg1;
- (void)setTextColor:(NSString *)arg1;
- (void)setTextOffset:(CGPoint)arg1;
- (void)setTextOpacity:(double)arg1;
- (NSString *)textColor;
- (CGPoint)textOffset;
- (double)textOpacity;

@end
