/* Generated by RuntimeBrowser
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
 */

@interface UIKeyboardTouchInfo : NSObject {
    long long  _continuousPathState;
    bool  _dragged;
    int  _fingerID;
    CGPoint  _initialDragPoint;
    int  _initialKeyState;
    CGPoint  _initialPoint;
    UIKBTree * _key;
    UIKBTree * _keyplane;
    bool  _maySuppressUpAction;
    unsigned long long  _processedTouchCount;
    UIKBTree * _slidOffKey;
    int  _stage;
    NSMutableArray * _touchHistory;
}

@property (nonatomic) long long continuousPathState;
@property (nonatomic) bool dragged;
@property (nonatomic) int fingerID;
@property (nonatomic) CGPoint initialDragPoint;
@property (nonatomic) int initialKeyState;
@property (nonatomic) CGPoint initialPoint;
@property (nonatomic, retain) UIKBTree *key;
@property (nonatomic, retain) UIKBTree *keyplane;
@property (nonatomic) bool maySuppressUpAction;
@property (nonatomic) unsigned long long processedTouchCount;
@property (nonatomic, retain) UIKBTree *slidOffKey;
@property (nonatomic) int stage;
@property (nonatomic, readonly) UIKBTouchState *touch;
@property (nonatomic, readonly) NSMutableArray *touchHistory;

- (void)addTouch:(UIKBTouchState *)arg1;
- (long long)continuousPathState;
- (void)dealloc;
- (bool)dragged;
- (int)fingerID;
- (id)init;
- (CGPoint)initialDragPoint;
- (int)initialKeyState;
- (CGPoint)initialPoint;
- (UIKBTree *)key;
- (UIKBTree *)keyplane;
- (bool)maySuppressUpAction;
- (unsigned long long)processedTouchCount;
- (void)setContinuousPathState:(long long)arg1;
- (void)setDragged:(bool)arg1;
- (void)setFingerID:(int)arg1;
- (void)setInitialDragPoint:(CGPoint)arg1;
- (void)setInitialKeyState:(int)arg1;
- (void)setInitialPoint:(CGPoint)arg1;
- (void)setKey:(UIKBTree *)arg1;
- (void)setKeyplane:(UIKBTree *)arg1;
- (void)setMaySuppressUpAction:(bool)arg1;
- (void)setProcessedTouchCount:(unsigned long long)arg1;
- (void)setSlidOffKey:(UIKBTree *)arg1;
- (void)setStage:(int)arg1;
- (UIKBTree *)slidOffKey;
- (int)stage;
- (UIKBTouchState *)touch;
- (NSMutableArray *)touchHistory;

@end
